apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ClusterRoleBinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: shankar
  namespace: default
roleRef:
  kind: ClusterRole
  name: ClusterRoleBinding
  apiGroup: rbac.authorization.k8s.io
