apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: shankar
  namespace: default
roleRef:
  kind: Role
  name: readonly
  apiGroup: rbac.authorization.k8s.io
